### ISSUE TITLE
Crash when opening the Connect Trakt screen on Android 6 and older

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#1066]
**Describe the bug**
Reported via email, confirmed crash on Crashlytics. The app crashes when tapping on "Connect Trakt" from the More screen.

**Smartphone (please complete the following information):**
 - OS: Android 6 and older
 - Version 2024.4.5

**Additional context**
It appears SVG gradients are only supported from Android 7 (API 23). This may be solved by simply using compat loading.

Stack trace:
```
Caused by org.xmlpull.v1.XmlPullParserException: Binary XML file line #16: invalid color state list tag gradient
       at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:218)
       at android.content.res.ColorStateList.createFromXml(ColorStateList.java:202)
       at android.content.res.Resources.loadColorStateListForCookie(Resources.java:3145)
       at android.content.res.Resources.loadColorStateList(Resources.java:3098)
       at android.content.res.TypedArray.getColor(TypedArray.java:439)
       at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1605)
       at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1584)
       at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:666)
       at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:571)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1220)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1129)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:3013)
       at android.content.res.Resources.loadDrawable(Resources.java:2857)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
       at android.widget.ImageView.<init>(ImageView.java:152)
       at android.widget.ImageView.<init>(ImageView.java:140)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:73)
       at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:233)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:152)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1654)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1705)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at com.battlelancer.seriesguide.databinding.FragmentConnectTraktCredentialsBinding.inflate(FragmentConnectTraktCredentialsBinding.java:149)
```

**Comment by UweTrottmann** [comment]
Will be fixed by #1067
