### ISSUE TITLE
.ui.OverviewActivity crash with java.lang.IllegalStateException

### ISSUE THREAD

**Issue by MartelliEnrico** [UweTrottmann/SeriesGuide#464]
Sometimes, when opening particular series (I find that with some of my Anime, probably the one with the name written in Kanji) a java.lang.IllegalStateException is thrown and the application is force closed.

This is what I got from the logcat:
```
06-20 23:33:10.506   750   760 I ActivityManager: START u0 {cmp=com.battlelancer.seriesguide/.ui.OverviewActivity (has extras)} from uid 10094 on display 0
06-20 23:33:10.509   750   760 V WindowManager: addAppToken: AppWindowToken{9f84fb7 token=Token{9db16b6 ActivityRecord{b46ae51 u0 com.battlelancer.seriesguide/.ui.OverviewActivity t1255}}} to stack=2 task=1255 at 1
06-20 23:33:10.573   750   953 V WindowManager: Adding window Window{a76de8d u0 com.battlelancer.seriesguide/com.battlelancer.seriesguide.ui.OverviewActivity} at 9 of 14 (after Window{e047519 u0 com.battlelancer.seriesguide/com.battlelancer.seriesguide.ui.ShowsActivity})
06-20 23:33:10.802   750   769 I ActivityManager: Displayed com.battlelancer.seriesguide/.ui.OverviewActivity: +280ms
06-20 23:33:10.919 12248 12450 D OpenGLRenderer: endAllStagingAnimators on 0x9e4ba880 (GridView) with handle 0x9cdd0160
06-20 23:33:11.066 12248 12450 W OpenGLRenderer: Layer exceeds max. dimensions supported by the GPU (1080x5452, max=4096x4096)
06-20 23:33:11.067 12248 12450 D OpenGLRenderer: Current memory usage / total memory usage (bytes):
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   TextureCache          2642944 / 75497472
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   LayerCache                  0 / 50331648 (numLayers = 0)
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:     Layer size 1088x384; isTextureLayer()=0; texid=29 fbo=3; refs=2
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   Layers total    1671168 (numLayers = 1)
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   RenderBufferCache           0 /  8388608
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   GradientCache               0 /  1048576
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   PathCache                1369 / 33554432
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   TessellationCache        6696 /  1048576
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   TextDropShadowCache         0 /  6291456
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   PatchCache                 64 /   131072
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   FontRenderer 0 A8     1048576 /  1048576
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   FontRenderer 0 RGBA         0 /        0
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   FontRenderer 0 total  1048576 /  1048576
06-20 23:33:11.067 12248 12450 D OpenGLRenderer: Other:
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   FboCache                    0 /        0
06-20 23:33:11.067 12248 12450 D OpenGLRenderer: Total memory usage:
06-20 23:33:11.067 12248 12450 D OpenGLRenderer:   5370817 bytes, 5.12 MB
06-20 23:33:11.080 12248 12248 E MessageQueue-JNI: Exception in MessageQueue callback: dispatchVsync
06-20 23:33:11.080 12248 12248 E MessageQueue-JNI: java.lang.IllegalStateException: Unable to create layer for LinearLayout
06-20 23:33:11.080 12248 12248 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-20 23:33:11.080 12248 12248 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:323)
06-20 23:33:11.080 12248 12248 E MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:135)
06-20 23:33:11.080 12248 12248 E MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:5401)
06-20 23:33:11.080 12248 12248 E MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Native Method)
06-20 23:33:11.080 12248 12248 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
06-20 23:33:11.080 12248 12248 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
06-20 23:33:11.080 12248 12248 D AndroidRuntime: Shutting down VM
06-20 23:33:11.099   750  6545 W ActivityManager: getRunningAppProcesses: caller 10094 does not hold REAL_GET_TASKS; limiting output
06-20 23:33:11.155 12248 12248 E AndroidRuntime: FATAL EXCEPTION: main
06-20 23:33:11.155 12248 12248 E AndroidRuntime: Process: com.battlelancer.seriesguide, PID: 12248
06-20 23:33:11.155 12248 12248 E AndroidRuntime: java.lang.IllegalStateException: Unable to create layer for LinearLayout
06-20 23:33:11.155 12248 12248 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-20 23:33:11.155 12248 12248 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:323)
06-20 23:33:11.155 12248 12248 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
06-20 23:33:11.155 12248 12248 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5401)
06-20 23:33:11.155 12248 12248 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-20 23:33:11.155 12248 12248 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
06-20 23:33:11.155 12248 12248 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
06-20 23:33:11.156   750  1466 W ActivityManager:   Force finishing activity com.battlelancer.seriesguide/.ui.OverviewActivity
06-20 23:33:11.160   750  1466 W ActivityManager:   Force finishing activity com.battlelancer.seriesguide/.ui.ShowsActivity
```

From this line `06-20 23:33:11.066 12248 12450 W OpenGLRenderer: Layer exceeds max. dimensions supported by the GPU (1080x5452, max=4096x4096)` I suspect the problem is that the page is too long (height larger than max) for the GPU to render.

[This stackoverflow](http://stackoverflow.com/questions/26626344/scene-transition-with-hero-elements-throws-layer-exceeds-max-dimensions-support) might be relevant.

**Comment by UweTrottmann** [comment]
Yes, I believe in overview large views are faded in. I'll have a look. Do you have an example show so I could try to reproduce this (otherwise it's hard to know if I fixed anything)?

**Comment by MartelliEnrico** [comment]
Yes, currently the one giving problem is "A certain scientific railgun".

**Comment by UweTrottmann** [comment]
Not seeing any issues (either with English or Japanese translation).

What device and Android version is this on? I suspect this is a device software issue, not SeriesGuide specific.

**Comment by MartelliEnrico** [comment]
I'm using the M Developer Preview, so this might be the problem.

Maybe we can wait till the new Developer Preview in July, and see if the
problem is solved.

Anyways, the height problem might be solved by collapsing the episode
description to a few lines, and open it on tap.

Il giorno dom 21 giu 2015, 11:22 Uwe Trottmann <notifications@github.com>
ha scritto:

**Comment by UweTrottmann** [comment]
Alright, won't fix. This bug smells like it's a preview build issue. Once M is released and this persists, let me know :)

**Comment by MartelliEnrico** [comment]
Little update: I just removed the Trakt connection, and now the problem seems fixed. When you tried did you have trakt enabled?

**Comment by UweTrottmann** [comment]
No, I didn't. Will hopefully have time to have another look this weekend. Thanks for reporting back!

**Comment by UweTrottmann** [comment]
Not heard back, so I'm assuming it works on the final release. Closing.
