### ISSUE TITLE
Few devices fail to migrate due to unexpected season table schema

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#563]
Their season table has column types and foreign key configurations that were never used. So this is likely a bug in the SQLite implementation on those devices.

**Affected devices**
- Xiami Mi 4c
- Wiko Pulp 4G
- AMIDuOS
- Wileyfox Swift 2 X
- Pixel XL
- ONEPLUS A3003
- Aquaris X5 Plus
- Galaxy S5

**Diffs**
ACTUAL
`series_id=Column{name='series_id', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0}`
EXPECTED
`series_id=Column{name='series_id', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}`

The `series_id` foreign key column always was `TEXT`.

ACTUAL
`foreignKeys=[ForeignKey{referenceTable='series', onDelete='CASCADE', onUpdate='CASCADE', columnNames=[series_id], referenceColumnNames=[_id]}]`
EXPECTED
`foreignKeys=[ForeignKey{referenceTable='series', onDelete='NO ACTION', onUpdate='NO ACTION', columnNames=[series_id], referenceColumnNames=[_id]}]`

The `series_id` foreign key column never had triggers specified (`NO_ACTION`). Like different defaults on those devices.

ACTUAL
`indices=null`
EXPECTED
`indices=[Index{name='index_seasons_series_id', unique=false, columns=[series_id]}]`

The index is added during migration (tested).

**Solution**
A fix would involve "simply" recreating the seasons table with a migration.

A workaround is to re-install the app and restore a backup or sign into Cloud to restore all data.

**Comment by UweTrottmann** [comment]
For some of the affected devices I get database closed exceptions during migration:
```
Caused by java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.battlelancer.seriesguide/databases/seriesdatabase
       at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1659)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
       at android.arch.persistence.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:242)
       at com.battlelancer.seriesguide.provider.SgRoomDatabase$Companion$MIGRATION_43_44$1.migrate(SgRoomDatabase.kt:148)
       at com.battlelancer.seriesguide.provider.SgRoomDatabase$Companion$MIGRATION_42_44$1.migrate(SgRoomDatabase.kt:113)
       at android.arch.persistence.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:85)
```

**Comment by UweTrottmann** [comment]
Stack trace of original issue:
```
Caused by java.lang.IllegalStateException: Migration didn't properly handle seasons(com.battlelancer.seriesguide.model.SgSeason).
 Expected:
TableInfo{name='seasons', columns={willaircount=Column{name='willaircount', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0}, watchcount=Column{name='watchcount', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0}, series_id=Column{name='series_id', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, _id=Column{name='_id', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=1}, season_totalcount=Column{name='season_totalcount', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0}, combinednr=Column{name='combinednr', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0}, seasonposter=Column{name='seasonposter', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, noairdatecount=Column{name='noairdatecount', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0}}, foreignKeys=[ForeignKey{referenceTable='series', onDelete='NO ACTION', onUpdate='NO ACTION', columnNames=[series_id], referenceColumnNames=[_id]}], indices=[Index{name='index_seasons_series_id', unique=false, columns=[series_id]}]}
 Found:
TableInfo{name='seasons', columns={willaircount=Column{name='willaircount', type='integer', affinity='3', notNull=false, primaryKeyPosition=0}, watchcount=Column{name='watchcount', type='integer', affinity='3', notNull=false, primaryKeyPosition=0}, series_id=Column{name='series_id', type='integer', affinity='3', notNull=false, primaryKeyPosition=0}, _id=Column{name='_id', type='integer', affinity='3', notNull=false, primaryKeyPosition=1}, season_totalcount=Column{name='season_totalcount', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0}, combinednr=Column{name='combinednr', type='integer', affinity='3', notNull=false, primaryKeyPosition=0}, seasonposter=Column{name='seasonposter', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, noairdatecount=Column{name='noairdatecount', type='integer', affinity='3', notNull=false, primaryKeyPosition=0}}, foreignKeys=[ForeignKey{referenceTable='series', onDelete='CASCADE', onUpdate='CASCADE', columnNames=[series_id], referenceColumnNames=[_id]}], indices=null}
       at com.battlelancer.seriesguide.provider.SgRoomDatabase_Impl$1.validateMigration(SgRoomDatabase_Impl.java:153)
       at android.arch.persistence.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:87)
       at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:133)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:96)
       at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
       at com.battlelancer.seriesguide.provider.SeriesGuideProvider.query(SeriesGuideProvider.java:224)
       at android.content.ContentProvider.query(ContentProvider.java:950)
       at android.content.ContentProvider$Transport.query(ContentProvider.java:210)
       at android.content.ContentResolver.query(ContentResolver.java:478)
       at android.content.ContentResolver.query(ContentResolver.java:422)
       at com.battlelancer.seriesguide.util.DBUtils.updateLatestEpisode(DBUtils.java:537)
```

**Comment by UweTrottmann** [comment]
At least confirmed for one user that they have used the legacy backup tool. That might have screwed things up.
