### ISSUE TITLE
Add TV Shows - could not talk to TMDb on android 4.4 k version

### ISSUE THREAD

**Issue by SenorSmartyPants** [UweTrottmann/SeriesGuide#703]
Seems like a recurrence of #636. Not sure if root cause is the same or not.

This used to occur very seldom, and then a few hours later everything would work fine. But it's pretty consistently failing now.

**Comment by UweTrottmann** [comment]
Do you see any warnings in the address bar (red padlock, etc.) if you try to access https://www.themoviedb.org/ or https://api.themoviedb.org/3/ (note: the last one will show an "Invalid API key" message as content, that's fine) on your device?

This test is not conclusive though, as your browser might have more modern encryption methods built-in than what Android (the operating system) provides to apps by default.

**Comment by SenorSmartyPants** [comment]
No errors or red padlocks when I tried those URLs. 

I used com.android.browser version 4.4.4-eng.lovejoy777.20141021.230457

And just realized I had access to the debug pull out on the right. Here's the timber log I could save.

```
01-06 12:13:15.237   ExtensionManager I Loading extension subscriptions
01-06 12:13:15.311   ExtensionManager D Restored subscription: ComponentInfo{com.battlelancer.seriesguide/com.battlelancer.seriesguide.extensions.WebSearchExtensionReceiver} token: faf7b17f-2926-41f6-b3e1-d7fa43f2c114
01-06 12:13:15.314   ExtensionManager D Restored subscription: ComponentInfo{com.battlelancer.seriesguide/com.battlelancer.seriesguide.extensions.YouTubeExtensionReceiver} token: b6650021-5166-4993-a993-5008137301bf
01-06 12:13:15.321   ExtensionManager I App restart: temporarily un-subscribing from all extensions.
01-06 12:13:15.324   ExtensionManager D disableExtension: unsubscribing from ComponentInfo{com.battlelancer.seriesguide/com.battlelancer.seriesguide.extensions.WebSearchExtensionReceiver}
01-06 12:13:15.330   ExtensionManager D disableExtension: unsubscribing from ComponentInfo{com.battlelancer.seriesguide/com.battlelancer.seriesguide.extensions.YouTubeExtensionReceiver}
01-06 12:13:15.334   ExtensionManager D Saving 0 subscriptions
01-06 12:13:15.412   ExtensionManager I App restart: re-subscribing to installed extensions.
01-06 12:13:15.414   ExtensionManager D enableExtension: subscribing to ComponentInfo{com.battlelancer.seriesguide/com.battlelancer.seriesguide.extensions.YouTubeExtensionReceiver}
01-06 12:13:15.418   ExtensionManager D enableExtension: subscribing to ComponentInfo{com.battlelancer.seriesguide/com.battlelancer.seriesguide.extensions.WebSearchExtensionReceiver}
01-06 12:13:15.421   ExtensionManager D Saving 2 subscriptions
01-06 12:13:18.339 LatestEpisodeUpdateTask D Updating next episodes for all shows
01-06 12:13:23.225 SgApp$providerInstallLi V Successfully installed GMS provider
01-06 12:14:06.474 LatestEpisodeUpdateTask D Updating next episodes for all shows
01-06 12:14:53.279              Utils E get shows w new episodes
javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x63dd3518: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x5c119d74:0x00000000)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.uwetrottmann.tmdb2.TmdbInterceptor.handleIntercept(TmdbInterceptor.java:70)
	at com.battlelancer.seriesguide.tmdbapi.SgTmdbInterceptor.intercept(SgTmdbInterceptor.java:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:92)
	at com.battlelancer.seriesguide.ui.search.ShowsDiscoverLiveData$WorkTask.getShowsWithNewEpisodes(ShowsDiscoverLiveData.kt:92)
	at com.battlelancer.seriesguide.ui.search.ShowsDiscoverLiveData$WorkTask.doInBackground(ShowsDiscoverLiveData.kt:62)
	at com.battlelancer.seriesguide.ui.search.ShowsDiscoverLiveData$WorkTask.doInBackground(ShowsDiscoverLiveData.kt:57)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x63dd3518: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x5c119d74:0x00000000)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
	... 33 more
```

**Comment by UweTrottmann** [comment]
Thanks for the log! `SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`: Looks like TMDb really turned off TLS v1.0 this time.

According to https://ankushg.com/posts/tls-1.2-on-android/ I should be able to create an update that enables TLS v1.2 on most Android 4.4 devices.

**Comment by UweTrottmann** [comment]
Hm, it appears everything still works as expected on an Android 4.4 emulated device. Did you reset your device or remove Google Play Services?

Side note: the above change will only work on devices that should currently work using Google Play Services to update the security provider.

**Comment by SenorSmartyPants** [comment]
The day after I sent the log I was able to connect again. I assumed this would break again, but it's currently working today.

Google Play Services (version 19.8.31) and Play store (v 17.9.17-all) are installed on this device.

No device reset, but there have been reboots.

**Comment by UweTrottmann** [comment]
Thanks for reporting. So nothing to do here for now.

**Comment by SenorSmartyPants** [comment]
It's been failing to connect again for the past several hours. Rebooted and still failing.

**Comment by SenorSmartyPants** [comment]
After a little more testing I think I understand how I was getting connected sometimes.

If I reboot my tablet, SG will fail to connect to TMDB on the add shows screen. Closing SG and/or rebooting tablet will not correct this. However, if I open browser app, load themoviedb.org (sometimes need to refresh site a couple times) and close SG (once or twice) then SG will start to connect to TMDB successfully.

It's a work around but kind of a pain. If you could deploy a better fix for this it would be appreciated.

Thanks.
