### ISSUE TITLE
Crash at app start if google-service.json is missing

### ISSUE THREAD

**Issue by ippschi** [UweTrottmann/SeriesGuide#785]
**Describe the issue**
Disclaimer: This issue occurs when building the app from code, it's not a _bug_ in a released version.

Without a `google-services.json` file in the `app` folder the app crashes at startup.

According to the [contribution guide](https://github.com/UweTrottmann/SeriesGuide/blob/dev/CONTRIBUTING.md) the "Debug builds should just work".

**To Reproduce**
1. Fork SeriesGuide and clone your fork
2. Select `dev` branch
3. Import the `SeriesGuide` folder as a new project in Android Studio
4. Select the `pureDebug` build variant (defined in `app/build.gradle`).

**Expected behavior**
The app starts without crashes.

**Additional context**
From the `build.gradle` (`app`) and the lines
```
if (project.file('google-services.json').exists()) {
    apply plugin: 'com.google.gms.google-services'
}
apply plugin: 'com.google.firebase.crashlytics'
```
I can see that measures were taken to prevent loading google-servies if no `google-service.json` file is present.
However, calling `FirebaseCrashlytics.getInstance()` without having `google-services.json` file in the `app` folder leads to the following exception:
```
2021-04-18 09:32:09.593 5052-5052/com.battlelancer.seriesguide E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.battlelancer.seriesguide, PID: 5052
    java.lang.RuntimeException: Unable to create application com.battlelancer.seriesguide.SgApp: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.battlelancer.seriesguide. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.battlelancer.seriesguide. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
        at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:270)
        at com.battlelancer.seriesguide.SgApp.initializeLogging(SgApp.kt:184)
        at com.battlelancer.seriesguide.SgApp.onCreate(SgApp.kt:144)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
```

When commenting out line 184 of SgApp.kt
```
FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(isSendErrors)
```
the crash does not occur anymore.

**Comment by UweTrottmann** [comment]
Thanks for reporting! Fixed with 0c017ce9.
