### ISSUE TITLE
Cloud download crash: wrapped.getHeaderField(key) must not be null

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#847]
Observed at random on emulator, but never seen in crash reports.
```
E/AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-1
    Process: com.battlelancer.seriesguide, PID: 10070
    java.lang.NullPointerException: wrapped.getHeaderField(key) must not be null
        at com.android.tools.appinspection.network.httpurl.TrackedHttpURLConnection.getHeaderField(TrackedHttpURLConnection.kt:317)
        at com.android.tools.appinspection.network.httpurl.HttpsURLConnectionWrapper.getHeaderField(HttpsURLConnectionWrapper.kt:182)
        at com.google.api.client.http.javanet.NetHttpResponse.getContentLength(NetHttpResponse.java:97)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1014)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
        at com.battlelancer.seriesguide.sync.HexagonShowSync.downloadShows(HexagonShowSync.kt:107)
        at com.battlelancer.seriesguide.sync.HexagonShowSync.download(HexagonShowSync.kt:52)
        at com.battlelancer.seriesguide.sync.HexagonSync.syncShows(HexagonSync.java:139)
        at com.battlelancer.seriesguide.sync.HexagonSync.sync(HexagonSync.java:66)
        at com.battlelancer.seriesguide.sync.SgSyncAdapter.onPerformSync(SgSyncAdapter.kt:143)
        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)
```

**Comment by UweTrottmann** [comment]
Actually this is an Android Studio tooling bug (see the first two package names in the stack trace): https://issuetracker.google.com/issues/219572925

Fixed in Bumblebee | 2021.1.1 Patch 3.
